### ISSUE TITLE
Changing a plugin from direct to staging then snapshot results in DFE

### ISSUE THREAD

**Issue by muralinimmagadda** [muralinimmagadda/sdk-sample#107]
`Mistakenly created my toolkit as direct, managed to create a dSource. Changed it to staging and tried to take a snapshot:`

`[2019-04-05 18:30:35,209][ERROR][util.ExceptionInstrumentationUtil#handleFatalThrowable:212][Worker-139|JOB-106|DB_SYNC(APPDATA_CONTAINER-4)][ACTION-313] Constructing fatal throwable`
`com.delphix.appliance.node.logging.exception.ConstructingFatalThrowableException: com.delphix.exception.DelphixFatalException: Toolkit workflow operation does not match the the source type. The requested workflow operation 'DIRECT_PRESNAPSHOT' corresponds to a non-staged toolkit while given source is a linked staged source.`
{{ at com.delphix.appliance.server.util.ExceptionInstrumentationUtil.handleFatalThrowable(ExceptionInstrumentationUtil.java:212)}}
{{ at com.delphix.appliance.server.util.ExceptionInstrumentationUtil.access$000(ExceptionInstrumentationUtil.java:32)}}
{{ at com.delphix.appliance.server.util.ExceptionInstrumentationUtil$2.sample(ExceptionInstrumentationUtil.java:164)}}
{{ at com.delphix.appliance.server.util.ExceptionInstrumentationUtil$2.sample(ExceptionInstrumentationUtil.java:160)}}
{{ at com.google.monitoring.runtime.instrumentation.ConstructorInstrumenter.invokeSamplers(ConstructorInstrumenter.java:207)}}
{{ at java.lang.RuntimeException.<init>(RuntimeException.java:63)}}
{{ at com.delphix.exception.DelphixFatalException.<init>(DelphixFatalException.java:25)}}
{{ at com.delphix.appliance.server.workflow.impl.WorkflowUtil$2.visit(WorkflowUtil.java:213)}}
{{ at com.delphix.appliance.server.workflow.impl.WorkflowUtil$2.visit(WorkflowUtil.java:157)}}
{{ at com.delphix.appliance.server.dco.ToolkitLinkedStagedSourceDO.uncheckedAccept(ToolkitLinkedStagedSourceDO.java:79)}}
{{ at com.delphix.appliance.server.workflow.impl.WorkflowUtil.getWorkflowScript(WorkflowUtil.java:156)}}
{{ at com.delphix.appliance.server.appdata.AppDataDataProvider.syncLinkedContainer(AppDataDataProvider.java:422)}}
{{ at com.delphix.appliance.server.lifecycle.impl.SyncJobManagerImpl.syncNoHooks(SyncJobManagerImpl.java:121)}}
{{ at com.delphix.appliance.server.lifecycle.impl.SyncJobManagerImpl.sync(SyncJobManagerImpl.java:110)}}
{{ at com.delphix.appliance.server.lifecycle.impl.DatabaseManagerImpl.doSync(DatabaseManagerImpl.java:1585)}}
{{ at com.delphix.appliance.server.lifecycle.impl.DatabaseManagerImpl.access$100(DatabaseManagerImpl.java:235)}}
{{ at com.delphix.appliance.server.lifecycle.impl.DatabaseManagerImpl$14.execute(DatabaseManagerImpl.java:1577)}}
{{ at com.delphix.appliance.server.jcm.impl.JobInstance$3.run(JobInstance.java:320)}}
{{ at com.delphix.appliance.server.dco.jobs.JobInterrupter.withThread(JobInterrupter.java:40)}}
{{ at com.delphix.appliance.server.jcm.impl.JobInstance.execute(JobInstance.java:315)}}
{{ at com.delphix.appliance.server.jcm.impl.JobLauncher$1.run(JobLauncher.java:30)}}
{{ at com.delphix.appliance.server.jcm.impl.JobTracker.runInJobContext(JobTracker.java:41)}}
{{ at com.delphix.appliance.server.jcm.impl.JobLauncher.execute(JobLauncher.java:25)}}
{{ at com.delphix.appliance.server.wms.impl.WorkerManagerImpl.run(WorkerManagerImpl.java:504)}}
{{ at com.delphix.appliance.server.wms.impl.WorkerControl.run(WorkerControl.java:125)}}
{{ ... 3 more}}
`Caused by: com.delphix.exception.DelphixFatalException: Toolkit workflow operation does not match the the source type. The requested workflow operation 'DIRECT_PRESNAPSHOT' corresponds to a non-staged toolkit while given source is a linked staged source.`
{{ ... 21 more}}

**Comment by muralinimmagadda** [comment]
➤ Eric Schrock commented:

Deleting the dSource was not enough, as a new one fails with:

A toolkit of type "Optional[ToolkitLinkedStagedSource]" must be linked with a source of type "Optional[AppDataLinkedStagedSource]", but was instead linked with a source of type "Optional[AppDataLinkedDirectSource]".
{{ }}

It looks like all the objects need to be deleted. It's probably the case that we should not allow uploading a plugin with a different type if any objects exist at all. Also, the above error message is incomprehensible - maybe it's not supposed to be a user error? And it talks a lot about toolkits, but they're plugins in the SDK docs.

**Comment by muralinimmagadda** [comment]
➤ Delphix Automation commented:

Transition made by Unito
